package com.company;

import org.apache.commons.math3.distribution.NormalDistribution;

import java.util.ArrayList;

public class SlideWindow {
    private int size;
    // suppose that time stamp is generated by System.currentTimeMillis-1600000000000
    private ArrayList<Long> time_queue;
    private long sum_of_stamp;
    private long sum_of_sq;

    public SlideWindow(int size){
        this.size = size;
        time_queue = new ArrayList<>();
        sum_of_stamp = 0;
        sum_of_sq = 0;
    }

    public void addTime(long new_time){
        if (time_queue.size() >= this.size) {
            sum_of_stamp -= time_queue.get(0);
            sum_of_sq -= time_queue.get(0) * time_queue.get(0);
            time_queue.remove(0);
        }
        time_queue.add(new_time);
        sum_of_stamp += new_time;
        sum_of_sq += new_time*new_time;
    }

    public double probabilityLater(long t){

    }
}
